# Generated by Django 3.1.2 on 2020-10-08 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("contenu", models.CharField(max_length=2000)),
                ("photo", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Benevole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available", models.BooleanField(default=True)),
                ("grade", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomfamille", models.CharField(max_length=200)),
                ("prenom", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=100)),
                ("codepostal", models.IntegerField(null=True)),
                ("mdp", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                (
                    "benevole",
                    models.ManyToManyField(
                        blank=True, related_name="missions", to="pourvous.Benevole"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Donateur",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pourvous.utilisateur",
                    ),
                ),
            ],
        ),
    ]
